# Generated by Django 2.2.3 on 2019-07-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.TextField(default='unknown', max_length=20, verbose_name='Статус'),
        ),
    ]
