# Generated by Django 2.2.3 on 2019-08-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0004_auto_20190719_2256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-sended_time'], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.RemoveField(
            model_name='message',
            name='system',
        ),
        migrations.AddField(
            model_name='message',
            name='systems',
            field=models.ManyToManyField(to='smsapp.System', verbose_name='Системы'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=11, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='systems',
            field=models.ManyToManyField(to='smsapp.System', verbose_name='Системы'),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(default='unknown', max_length=20, verbose_name='Статус'),
        ),
    ]
